version: "3.9"

networks:
  default:
    driver: bridge

services:

  mariadb:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MARIADB_USER: helios
      MARIADB_PASSWORD: Helios_2001!
      MARIADB_ROOT_PASSWORD: Helios_2001!
      MARIADB_DATABASE: helios

  influxdb:
    image: influxdb:2.7-alpine
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=helios
      - DOCKER_INFLUXDB_INIT_PASSWORD=Helios_2001!
      - DOCKER_INFLUXDB_INIT_ORG=helios
      - DOCKER_INFLUXDB_INIT_BUCKET=helios_powerflow

  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8088:80
    environment:
      PMA_HOST: mariadb
      MARIADB_ROOT_PASSWORD: Helios_2001!

volumes:
  mariadb-data:
  influxdb-data:
