# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Helios

theme:
  name: material

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
